//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLDRL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CVHT
    {
        public CVHT()
        {
            this.Lops = new HashSet<Lop>();
        }
    
        public int ID { get; set; }
        public string Ten { get; set; }
        public string SDT { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public Nullable<bool> Gioitinh { get; set; }
        public string Diachi { get; set; }
        public Nullable<bool> Admin { get; set; }
    
        public virtual ICollection<Lop> Lops { get; set; }
    }
}
