//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLDRL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Danhgia
    {
        public int ID { get; set; }
        public Nullable<int> SinhvienID { get; set; }
        public Nullable<int> TieuchiID { get; set; }
        public Nullable<int> Diemdanhgia { get; set; }
        public Nullable<System.DateTime> Ngaydanhgia { get; set; }
    
        public virtual Sinhvien Sinhvien { get; set; }
        public virtual Tieuchi Tieuchi { get; set; }
    }
}
