//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLDRL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lop
    {
        public Lop()
        {
            this.Sinhviens = new HashSet<Sinhvien>();
        }
    
        public int ID { get; set; }
        public string Ten { get; set; }
        public Nullable<int> GVCN_ID { get; set; }
    
        public virtual CVHT CVHT { get; set; }
        public virtual ICollection<Sinhvien> Sinhviens { get; set; }
    }
}
