//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLDRL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sinhvien
    {
        public Sinhvien()
        {
            this.Danhgias = new HashSet<Danhgia>();
        }
    
        public int ID { get; set; }
        public string Ten { get; set; }
        public Nullable<System.DateTime> Ngaysinh { get; set; }
        public Nullable<bool> Gioitinh { get; set; }
        public int LopID { get; set; }
    
        public virtual ICollection<Danhgia> Danhgias { get; set; }
        public virtual Lop Lop { get; set; }
    }
}
